export const categories = [
  { slug: "chal", name: "চাল", nameBn: "চাল", icon: "🍚" },
  { slug: "dal", name: "ডাল", nameBn: "ডাল", icon: "🫘" },
  { slug: "tel", name: "তেল", nameBn: "তেল", icon: "🛢️" },
  { slug: "sobji", name: "সবজি", nameBn: "সবজি", icon: "🥬" },
  { slug: "mach", name: "মাছ", nameBn: "মাছ", icon: "🐟" },
  { slug: "mangsho", name: "মাংস", nameBn: "মাংস", icon: "🍗" },
  { slug: "dim-dui", name: "ডিম-দুধ", nameBn: "ডিম-দুধ", icon: "🥛" },
  { slug: "mosla", name: "মসলা", nameBn: "মসলা", icon: "🌶️" },
];

const markets = [
  { market: "ধানমন্ডি বাজার", division: "ঢাকা" },
  { market: "মোহাম্মদপুর বাজার", division: "ঢাকা" },
  { market: "উত্তরা বাজার", division: "ঢাকা" },
  { market: "কক্সবাজার বাজার", division: "চট্টগ্রাম" },
  { market: "সিলেট সদর বাজার", division: "সিলেট" },
  { market: "রাজশাহী বাজার", division: "রাজশাহী" },
  { market: "খুলনা বাজার", division: "খুলনা" },
  { market: "বরিশাল বাজার", division: "বরিশাল" },
];

function genMarkets(basePrice, variance = 10) {
  return markets.map((m) => {
    const min = Math.round(basePrice * (1 - variance / 100));
    const max = Math.round(basePrice * (1 + variance / 100));
    const minJitter = Math.round((Math.random() - 0.5) * basePrice * 0.05);
    const maxJitter = Math.round((Math.random() - 0.5) * basePrice * 0.05);
    return {
      ...m,
      min: Math.max(1, min + minJitter),
      max: Math.max(1, max + maxJitter),
    };
  });
}

function calcChange(today, yesterday) {
  const pct = Number(((today - yesterday) / yesterday * 100).toFixed(1));
  let dir = "flat";
  if (pct > 0.3) dir = "up";
  else if (pct < -0.3) dir = "down";
  return { dir, pct: Math.abs(pct) };
}

export const products = [
  // চাল
  {
    id: 1,
    slug: "miniket-chal",
    nameBn: "মিনিকেট চাল",
    category: "chal",
    categoryNameBn: "চাল",
    categoryIcon: "🍚",
    unit: "kg",
    image: "🍚",
    today: 78,
    yesterday: 76,
    lastWeek: 75,
    lastMonth: 72,
    change: calcChange(78, 76),
    markets: genMarkets(78, 8),
  },
  {
    id: 2,
    slug: "najir-shail-chal",
    nameBn: "নাজিরশাইল চাল",
    category: "chal",
    categoryNameBn: "চাল",
    categoryIcon: "🍚",
    unit: "kg",
    image: "🌾",
    today: 95,
    yesterday: 93,
    lastWeek: 92,
    lastMonth: 90,
    change: calcChange(95, 93),
    markets: genMarkets(95, 7),
  },
  {
    id: 3,
    slug: "br-28-chal",
    nameBn: "বিআর-২৮ চাল",
    category: "chal",
    categoryNameBn: "চাল",
    categoryIcon: "🍚",
    unit: "kg",
    image: "🍚",
    today: 65,
    yesterday: 65,
    lastWeek: 66,
    lastMonth: 64,
    change: calcChange(65, 65),
    markets: genMarkets(65, 6),
  },
  {
    id: 4,
    slug: "chinigura-chal",
    nameBn: "চিনিগুড়া চাল",
    category: "chal",
    categoryNameBn: "চাল",
    categoryIcon: "🍚",
    unit: "kg",
    image: "🍙",
    today: 120,
    yesterday: 118,
    lastWeek: 115,
    lastMonth: 110,
    change: calcChange(120, 118),
    markets: genMarkets(120, 8),
  },

  // ডাল
  {
    id: 5,
    slug: "moshur-dal",
    nameBn: "মসুর ডাল",
    category: "dal",
    categoryNameBn: "ডাল",
    categoryIcon: "🫘",
    unit: "kg",
    image: "🫘",
    today: 140,
    yesterday: 138,
    lastWeek: 135,
    lastMonth: 130,
    change: calcChange(140, 138),
    markets: genMarkets(140, 10),
  },
  {
    id: 6,
    slug: "chholar-dal",
    nameBn: "ছোলার ডাল",
    category: "dal",
    categoryNameBn: "ডাল",
    categoryIcon: "🫘",
    unit: "kg",
    image: "🟡",
    today: 110,
    yesterday: 112,
    lastWeek: 115,
    lastMonth: 120,
    change: calcChange(110, 112),
    markets: genMarkets(110, 8),
  },
  {
    id: 7,
    slug: "motor-dal",
    nameBn: "মটর ডাল",
    category: "dal",
    categoryNameBn: "ডাল",
    categoryIcon: "🫘",
    unit: "kg",
    image: "🟤",
    today: 155,
    yesterday: 153,
    lastWeek: 150,
    lastMonth: 145,
    change: calcChange(155, 153),
    markets: genMarkets(155, 9),
  },
  {
    id: 8,
    slug: "mug-dal",
    nameBn: "মুগ ডাল",
    category: "dal",
    categoryNameBn: "ডাল",
    categoryIcon: "🫘",
    unit: "kg",
    image: "🟢",
    today: 185,
    yesterday: 187,
    lastWeek: 190,
    lastMonth: 195,
    change: calcChange(185, 187),
    markets: genMarkets(185, 7),
  },

  // তেল
  {
    id: 9,
    slug: "soyabean-tel",
    nameBn: "সয়াবিন তেল",
    category: "tel",
    categoryNameBn: "তেল",
    categoryIcon: "🛢️",
    unit: "liter",
    image: "🛢️",
    today: 135,
    yesterday: 134,
    lastWeek: 132,
    lastMonth: 130,
    change: calcChange(135, 134),
    markets: genMarkets(135, 5),
  },
  {
    id: 10,
    slug: "mustard-tel",
    nameBn: "সরিষার তেল",
    category: "tel",
    categoryNameBn: "তেল",
    categoryIcon: "🛢️",
    unit: "liter",
    image: "🫗",
    today: 210,
    yesterday: 208,
    lastWeek: 205,
    lastMonth: 200,
    change: calcChange(210, 208),
    markets: genMarkets(210, 8),
  },
  {
    id: 11,
    slug: "sunflower-tel",
    nameBn: "সানফ্লাওয়ার তেল",
    category: "tel",
    categoryNameBn: "তেল",
    categoryIcon: "🛢️",
    unit: "liter",
    image: "🌻",
    today: 155,
    yesterday: 157,
    lastWeek: 160,
    lastMonth: 165,
    change: calcChange(155, 157),
    markets: genMarkets(155, 6),
  },

  // সবজি
  {
    id: 12,
    slug: "alu",
    nameBn: "আলু",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🥔",
    today: 35,
    yesterday: 36,
    lastWeek: 38,
    lastMonth: 40,
    change: calcChange(35, 36),
    markets: genMarkets(35, 15),
  },
  {
    id: 13,
    slug: "piyaj",
    nameBn: "পেঁয়াজ",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🧅",
    today: 90,
    yesterday: 88,
    lastWeek: 85,
    lastMonth: 80,
    change: calcChange(90, 88),
    markets: genMarkets(90, 12),
  },
  {
    id: 14,
    slug: "morich",
    nameBn: "কাঁচা মরিচ",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🌶️",
    today: 120,
    yesterday: 125,
    lastWeek: 130,
    lastMonth: 140,
    change: calcChange(120, 125),
    markets: genMarkets(120, 20),
  },
  {
    id: 15,
    slug: "tomato",
    nameBn: "টমেটো",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🍅",
    today: 60,
    yesterday: 58,
    lastWeek: 55,
    lastMonth: 50,
    change: calcChange(60, 58),
    markets: genMarkets(60, 18),
  },
  {
    id: 16,
    slug: "dherosh",
    nameBn: "ঢেঁড়স",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🥒",
    today: 45,
    yesterday: 45,
    lastWeek: 48,
    lastMonth: 55,
    change: calcChange(45, 45),
    markets: genMarkets(45, 15),
  },
  {
id: 17,
    slug: "begun",
    nameBn: "বেগুন",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🍆",
    today: 50,
    yesterday: 52,
    lastWeek: 55,
    lastMonth: 60,
    change: calcChange(50, 52),
    markets: genMarkets(50, 16),
  },
  {
    id: 18,
    slug: "phool-kopi",
    nameBn: "ফুলকপি",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🥦",
    today: 80,
    yesterday: 78,
    lastWeek: 75,
    lastMonth: 70,
    change: calcChange(80, 78),
    markets: genMarkets(80, 12),
  },
  {
    id: 19,
    slug: "bandha-kopi",
    nameBn: "বাঁধাকপি",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🥬",
    today: 30,
    yesterday: 32,
    lastWeek: 35,
    lastMonth: 40,
    change: calcChange(30, 32),
    markets: genMarkets(30, 20),
  },
  {
    id: 20,
    slug: "carrot",
    nameBn: "গাজর",
    category: "sobji",
    categoryNameBn: "সবজি",
    categoryIcon: "🥬",
    unit: "kg",
    image: "🥕",
    today: 55,
    yesterday: 55,
    lastWeek: 58,
    lastMonth: 65,
    change: calcChange(55, 55),
    markets: genMarkets(55, 14),
  },

  // মাছ
  {
    id: 21,
    slug: "rui-mach",
    nameBn: "রুই মাছ",
    category: "mach",
    categoryNameBn: "মাছ",
    categoryIcon: "🐟",
    unit: "kg",
    image: "🐟",
    today: 320,
    yesterday: 310,
    lastWeek: 300,
    lastMonth: 280,
    change: calcChange(320, 310),
    markets: genMarkets(320, 10),
  },
  {
    id: 22,
    slug: "katla-mach",
    nameBn: "কাতলা মাছ",
    category: "mach",
    categoryNameBn: "মাছ",
    categoryIcon: "🐟",
    unit: "kg",
    image: "🐠",
    today: 350,
    yesterday: 340,
    lastWeek: 330,
    lastMonth: 300,
    change: calcChange(350, 340),
    markets: genMarkets(350, 9),
  },
  {
    id: 23,
    slug: "hilsa-mach",
    nameBn: "ইলিশ মাছ",
    category: "mach",
    categoryNameBn: "মাছ",
    categoryIcon: "🐟",
    unit: "kg",
    image: "🐟",
    today: 1200,
    yesterday: 1150,
    lastWeek: 1100,
    lastMonth: 1000,
    change: calcChange(1200, 1150),
    markets: genMarkets(1200, 15),
  },
  {
    id: 24,
    slug: "pangas-mach",
    nameBn: "পাঙ্গাস মাছ",
    category: "mach",
    categoryNameBn: "মাছ",
    categoryIcon: "🐟",
    unit: "kg",
    image: "🐟",
    today: 220,
    yesterday: 225,
    lastWeek: 230,
    lastMonth: 240,
    change: calcChange(220, 225),
    markets: genMarkets(220, 12),
  },
  {
    id: 25,
    slug: "chingri",
    nameBn: "চিংড়ি",
    category: "mach",
    categoryNameBn: "মাছ",
    categoryIcon: "🐟",
    unit: "kg",
    image: "🦐",
    today: 650,
    yesterday: 630,
    lastWeek: 600,
    lastMonth: 550,
    change: calcChange(650, 630),
    markets: genMarkets(650, 18),
  },

  // মাংস
  {
    id: 26,
    slug: "murgi-mangsho",
    nameBn: "মুরগির মাংস",
    category: "mangsho",
    categoryNameBn: "মাংস",
    categoryIcon: "🍗",
    unit: "kg",
    image: "🍗",
    today: 280,
    yesterday: 275,
    lastWeek: 270,
    lastMonth: 260,
    change: calcChange(280, 275),
    markets: genMarkets(280, 8),
  },
  {
    id: 27,
    slug: "gorur-mangsho",
    nameBn: "গরুর মাংস",
    category: "mangsho",
    categoryNameBn: "মাংস",
    categoryIcon: "🍗",
    unit: "kg",
    image: "🥩",
    today: 780,
    yesterday: 770,
    lastWeek: 760,
    lastMonth: 750,
    change: calcChange(780, 770),
    markets: genMarkets(780, 7),
  },
  {
    id: 28,
    slug: "khashir-mangsho",
    nameBn: "খাসির মাংস",
    category: "mangsho",
    categoryNameBn: "মাংস",
    categoryIcon: "🍗",
    unit: "kg",
    image: "🍖",
    today: 850,
    yesterday: 840,
    lastWeek: 830,
    lastMonth: 800,
    change: calcChange(850, 840),
    markets: genMarkets(850, 8),
  },

  // ডিম-দুধ
  {
    id: 29,
    slug: "dim",
    nameBn: "ডিম",
    category: "dim-dui",
    categoryNameBn: "ডিম-দুধ",
    categoryIcon: "🥛",
    unit: "dozen",
    image: "🥚",
    today: 130,
    yesterday: 128,
    lastWeek: 125,
    lastMonth: 120,
    change: calcChange(130, 128),
    markets: genMarkets(130, 10),
  },
  {
    id: 30,
    slug: "dudh",
    nameBn: "দুধ",
    category: "dim-dui",
    categoryNameBn: "ডিম-দুধ",
    categoryIcon: "🥛",
    unit: "liter",
    image: "🥛",
    today: 90,
    yesterday: 88,
    lastWeek: 85,
    lastMonth: 80,
    change: calcChange(90, 88),
    markets: genMarkets(90, 8),
  },
  {
    id: 31,
    slug: "ghee",
    nameBn: "ঘি",
    category: "dim-dui",
    categoryNameBn: "ডিম-দুধ",
    categoryIcon: "🥛",
    unit: "kg",
    image: "🧈",
    today: 850,
    yesterday: 845,
    lastWeek: 840,
    lastMonth: 820,
    change: calcChange(850, 845),
    markets: genMarkets(850, 6),
  },

  // মসলা
  {
    id: 32,
    slug: "morich-gura",
    nameBn: "মরিচ গুড়া",
    category: "mosla",
    categoryNameBn: "মসলা",
    categoryIcon: "🌶️",
    unit: "kg",
    image: "🌶️",
    today: 380,
    yesterday: 375,
    lastWeek: 370,
    lastMonth: 360,
    change: calcChange(380, 375),
    markets: genMarkets(380, 10),
  },
  {
    id: 33,
    slug: "holud",
    nameBn: "হলুদ",
    category: "mosla",
    categoryNameBn: "মসলা",
    categoryIcon: "🌶️",
    unit: "kg",
    image: "🟡",
    today: 250,
    yesterday: 255,
    lastWeek: 260,
    lastMonth: 270,
    change: calcChange(250, 255),
    markets: genMarkets(250, 12),
  },
  {
    id: 34,
    slug: "jeera",
    nameBn: "জিরা",
    category: "mosla",
    categoryNameBn: "মসলা",
    categoryIcon: "🌶️",
    unit: "kg",
    image: "⚫",
    today: 420,
    yesterday: 410,
    lastWeek: 400,
    lastMonth: 380,
    change: calcChange(420, 410),
    markets: genMarkets(420, 9),
  },
  {
    id: 35,
    slug: "dhonia",
    nameBn: "ধনে",
    category: "mosla",
    categoryNameBn: "মসলা",
    categoryIcon: "🌶️",
    unit: "kg",
    image: "🟤",
    today: 320,
    yesterday: 315,
    lastWeek: 310,
    lastMonth: 300,
    change: calcChange(320, 315),
    markets: genMarkets(320, 11),
  },
  {
    id: 36,
    slug: "ada",
    nameBn: "আদা",
    category: "mosla",
    categoryNameBn: "মসলা",
    categoryIcon: "🌶️",
    unit: "kg",
    image: "🫚",
    today: 200,
    yesterday: 195,
    lastWeek: 190,
    lastMonth: 180,
    change: calcChange(200, 195),
    markets: genMarkets(200, 15),
  },
  {
    id: 37,
    slug: "rosun",
    nameBn: "রসুন",
    category: "mosla",
    categoryNameBn: "মসলা",
    categoryIcon: "🌶️",
    unit: "kg",
    image: "🧄",
    today: 280,
    yesterday: 285,
    lastWeek: 290,
    lastMonth: 300,
    change: calcChange(280, 285),
    markets: genMarkets(280, 10),
  },
];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug) {
  return products.filter((p) => p.category === categorySlug);
}

export function getTopRisers(limit = 6) {
  return [...products]
    .filter((p) => p.change.dir === "up")
    .sort((a, b) => b.change.pct - a.change.pct)
    .slice(0, limit);
}

export function getTopFallers(limit = 6) {
  return [...products]
    .filter((p) => p.change.dir === "down")
    .sort((a, b) => b.change.pct - a.change.pct)
    .slice(0, limit);
}

export function getCategoryBySlug(slug) {
  return categories.find((c) => c.slug === slug);
}
